nmnum=int(input())
if(nmnum==0):
  print("Zero")
elif(nmnum==1):
  print("One")
elif(nmnum==2):
  print("Two")
elif(nmnum==3):
  print("Three")
elif(nmnum==4):
  print("Four")
elif(nmnum==5):
  print("Five")
elif(nmnum==6):
  print("Six")
elif(nmnum==7):
  print("Seven")
elif(nmnum==8):
  print("Eight")
elif(nmnum==9):
  print("Nine")
elif(nmnum==10):
  print("Ten")
else:
  print("invalid")
